export const ENV_KEYS = {
  DB_HOST: 'DB_HOST',
  DB_NAME: 'DB_NAME',
  DB_PORT: 'DB_PORT',
  DB_USERNAME: 'DB_USERNAME',
  DB_PASSWORD: 'DB_PASSWORD',

  PASSWORD_HASH: 'PASSWORD_HASH',

  ACCESS_TOKEN_EXPIRATION: 'ACCESS_TOKEN_EXPIRATION',
  REFRESH_TOKEN_EXPIRATION: 'REFRESH_TOKEN_EXPIRATION',
  JWT_SECRET: 'JWT_SECRET',

  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',

  SESSION_SECRET: 'SESSION_SECRET',

  EXCEPTIONAL_DOMEN: 'EXCEPTIONAL_DOMEN',
  ALLOWED_DOMEN: 'ALLOWED_DOMEN',
  SPREADSHEET_ID: 'SPREADSHEET_ID',
  SHEET_NAME: 'SHEET_NAME',

  EMAIL: 'EMAIL',
  EMAIL_PASSWORD: 'EMAIL_PASSWORD',
};
